name: CI/CD Deploy Amra App

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FRONT_IMAGE: muammar88/amra_saas_client:v1.0
      BACK_IMAGE: muammar88/amra_saas_server:v1.0
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin

    - name: Build and push client image
      run: |
        docker build -t $FRONT_IMAGE ./client
        docker push $FRONT_IMAGE

    - name: Build and push backend image
      run: |
        docker build -t $BACK_IMAGE ./server
        docker push $BACK_IMAGE

    - name: Deploy to Ubuntu server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.SERVER_IP }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
        
          cd ./amra
          
          # Pull latest images
          docker pull $FRONT_IMAGE
          docker pull $BACK_IMAGE

          # Stop and remove containers if exist
          docker-compose -f docker-compose.dev.yml down || true

          # Start services using docker-compose
          docker-compose -f docker-compose.dev.yml up -d

          # Run Sequelize migration and seed scripts
          cd ./server  # Pastikan berada di direktori yang benar
          npx sequelize-cli db:migrate:undo:all
          npx sequelize-cli db:migrate
          npx sequelize-cli db:seed:all
